import { createContext, useContext, useEffect, useMemo, useState, type Dispatch, type FormEvent, type ReactNode, type SetStateAction } from 'react'
import { Link, NavLink, useNavigate, useParams, useSearchParams } from 'react-router-dom'

type ExpenseList = { id: string; name: string; createdAt: string }
type Purchase = { id: string; listId: string; amount: number; description: string; date: string; createdAt: string }
type Trip = { id: string; type: 'Outbound' | 'Return'; amount: number }; type TransportRecord = { id: string; date: string; trips: Trip[]; createdAt: string }; type Store = { lists: ExpenseList[]; purchases: Purchase[]; transportRecords: TransportRecord[] }
const STORAGE_KEY = 'personal-expenses-stage2-v1'
function loadStore(): Store {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return { lists: [], purchases: [], transportRecords: [] }
    const parsed = JSON.parse(raw) as Partial<Store>
    return { lists: Array.isArray(parsed.lists) ? parsed.lists.filter(x => x && typeof x.id === 'string' && typeof x.name === 'string') : [], purchases: Array.isArray(parsed.purchases) ? parsed.purchases.filter(x => x && typeof x.id === 'string' && typeof x.listId === 'string' && Number.isFinite(x.amount) && typeof x.date === 'string') : [], transportRecords: Array.isArray(parsed.transportRecords) ? parsed.transportRecords.filter((x: any) => x && typeof x.id === 'string' && typeof x.date === 'string' && Array.isArray(x.trips) && x.trips.every((t: any) => t && typeof t.id === 'string' && (t.type === 'Outbound' || t.type === 'Return') && Number.isFinite(t.amount) && t.amount > 0)) : [] }
  } catch { return { lists: [], purchases: [], transportRecords: [] } }
}
const StoreContext = createContext<{ store: Store; setStore: Dispatch<SetStateAction<Store>> } | null>(null)
export function ExpenseStoreProvider({ children }: { children: ReactNode }) {
  const [store, setStore] = useState<Store>(loadStore)
  useEffect(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(store)) } catch { /* storage may be unavailable */ } }, [store])
  return <StoreContext.Provider value={{ store, setStore }}>{children}</StoreContext.Provider>
}
function useStore() {
  const value = useContext(StoreContext)
  if (!value) throw new Error('ExpenseStoreProvider is missing')
  return value
}
const monthKey = (date: string) => date.slice(0, 7)
const monthLabel = (month: string) => { const [y, m] = month.split('-').map(Number); return new Date(y, m - 1, 1).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) }
const money = (amount: number) => `${new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(amount)} SYP`
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }
const thisMonth = () => today().slice(0, 7)

export function ExpensesPage() {
  const sections = [{ label: 'Personal Expenses', to: '/expenses/personal', available: true }, { label: 'University Expenses', to: '#', available: false }, { label: 'Commitments', to: '#', available: false }, { label: 'Health', to: '#', available: false }]
  return <section className="expense-page"><div className="page-heading"><p className="eyebrow">Expenses</p><h1>Expenses</h1><p className="page-description">Choose an expense section to continue.</p></div><div className="section-grid">{sections.map(s => s.available ? <NavLink key={s.label} to={s.to} className="section-card section-card--interactive"><span>{s.label}</span><span>→</span></NavLink> : <div key={s.label} className="section-card section-card--disabled" aria-disabled="true"><span>{s.label}</span><span className="muted-note">Coming later</span></div>)}</div></section>
}

export function PersonalExpensesPage() {
  const { store, setStore } = useStore(); const [name, setName] = useState(''); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [month, setMonth] = useState(thisMonth()); const navigate = useNavigate()
  const create = (e: FormEvent) => { e.preventDefault(); const clean = name.trim().replace(/\s+/g, ' '); if (!clean) { setError('Enter a name for this list.'); return } if (clean.length > 60) { setError('List name must be 60 characters or fewer.'); return } if (store.lists.some(l => l.name.toLocaleLowerCase() === clean.toLocaleLowerCase())) { setError('A list with this name already exists.'); return } const id = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`; setStore(s => ({ ...s, lists: [...s.lists, { id, name: clean, createdAt: new Date().toISOString() }] })); setName(''); setError(''); setShowForm(false); navigate(`/expenses/personal/${id}`) }
  return <section className="expense-page"><div className="breadcrumb"><Link to="/expenses">Expenses</Link><span>/</span><span>Personal Expenses</span></div><div className="page-heading page-heading--row"><div><p className="eyebrow">Personal Expenses</p><h1>Personal Expenses</h1><p className="page-description">Create your own lists and track expenses month by month.</p></div><button className="primary-action" onClick={() => { setShowForm(v => !v); setError('') }}>＋ Add list</button></div>
  {showForm && <form className="panel create-form" onSubmit={create}><label htmlFor="list-name">List name</label><div className="form-row"><input id="list-name" autoFocus maxLength={60} value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Food, Coffee, Transport"/><button className="primary-action" type="submit">Create list</button></div>{error && <p className="form-error" role="alert">{error}</p>}<p className="helper-text">Choose any name up to 60 characters.</p></form>}
  <div className="month-control"><label htmlFor="lists-month">Summary month</label><input id="lists-month" type="month" value={month} onChange={e => setMonth(e.target.value || thisMonth())}/></div>
  <div className="list-cards"><Link to="/expenses/personal/transport" className="personal-list-card"><div className="list-card-top"><span className="list-icon">↔</span><span className="section-card__arrow">→</span></div><h2>المواصلات</h2><p>Track each trip and daily transport costs</p><strong>{money(store.transportRecords.filter(r => monthKey(r.date) === month).reduce((sum,r)=>sum+r.trips.reduce((a,t)=>a+t.amount,0),0))}</strong></Link>{store.lists.map(list => { const items = store.purchases.filter(p => p.listId === list.id && monthKey(p.date) === month); const total = items.reduce((sum, p) => sum + p.amount, 0); return <Link key={list.id} className="personal-list-card" to={`/expenses/personal/${list.id}`}><div className="list-card-top"><span className="list-icon">↗</span><span className="section-card__arrow">→</span></div><h2>{list.name}</h2><p>{items.length ? `${items.length} purchase${items.length === 1 ? '' : 's'} this month` : 'No purchases this month'}</p><strong>{money(total)}</strong></Link> })}</div>{store.lists.length === 0 && <div className="empty-state"><h2>No personal expense lists yet</h2><p>Create your first list to start recording purchases.</p><button className="secondary-action" onClick={() => setShowForm(true)}>Create first list</button></div>}</section>
}

const tabs = [{ label: 'Overview', suffix: '' }, { label: 'Purchases', suffix: '/purchases' }, { label: 'Analysis', suffix: '/analysis' }, { label: 'Entry History', suffix: '/history' }]
function MonthPicker({ month, onChange }: { month: string; onChange: (m: string) => void }) { return <div className="month-control"><label htmlFor="expense-month">Month</label><input id="expense-month" type="month" value={month} onChange={e => onChange(e.target.value || thisMonth())}/></div> }
function useListData() {
  const { listId = '' } = useParams(); const { store, setStore } = useStore(); const list = store.lists.find(l => l.id === listId); const [params, setParams] = useSearchParams(); const month = params.get('month') || thisMonth()
  const setMonth = (m: string) => setParams(prev => { const p = new URLSearchParams(prev); p.set('month', m); return p }, { replace: true })
  const purchases = useMemo(() => store.purchases.filter(p => p.listId === listId && monthKey(p.date) === month).sort((a,b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt)), [store.purchases, listId, month])
  return { listId, store, setStore, list, month, setMonth, purchases, total: purchases.reduce((s,p) => s + p.amount, 0) }
}
function PersonalListLayout({ children, listName }: { children: ReactNode; listName?: string }) {
  const { listId = '' } = useParams(); const { store } = useStore(); const list = store.lists.find(l => l.id === listId); const base = `/expenses/personal/${listId}`
  if (!list) return <section className="expense-page"><div className="breadcrumb"><Link to="/expenses/personal">Personal Expenses</Link></div><div className="empty-state"><h2>List not found</h2><p>This list may have been removed or the link is invalid.</p><Link className="secondary-action link-button" to="/expenses/personal">Back to personal expenses</Link></div></section>
  return <section className="expense-page list-page"><div className="breadcrumb"><Link to="/expenses">Expenses</Link><span>/</span><Link to="/expenses/personal">Personal Expenses</Link><span>/</span><span>{list.name}</span></div><div className="list-heading"><p className="eyebrow">Personal Expenses</p><h1>{listName || list.name}</h1></div><nav className="sub-navigation" aria-label="Expense list navigation">{tabs.map(t => <NavLink key={t.label} to={`${base}${t.suffix}${window.location.search}`} end={!t.suffix} className={({isActive}) => `sub-navigation__link${isActive ? ' sub-navigation__link--active' : ''}`}>{t.label}</NavLink>)}</nav><div className="sub-page-content">{children}</div></section>
}
function PurchaseForm({ listId, onSaved }: { listId: string; onSaved?: () => void }) {
 const { setStore } = useStore(); const [amount,setAmount] = useState(''); const [description,setDescription] = useState(''); const [date,setDate] = useState(today()); const [error,setError] = useState(''); const [success,setSuccess] = useState(false)
 const submit = (e: FormEvent) => { e.preventDefault(); const value = Number(amount); if (!amount.trim() || !Number.isFinite(value) || value <= 0) { setError('Enter an amount greater than zero.'); return } if (!description.trim()) { setError('Enter a description.'); return } if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(new Date(`${date}T12:00:00`).getTime())) { setError('Choose a valid expense date.'); return } const purchase: Purchase = { id: `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`, listId, amount: Math.round(value * 100) / 100, description: description.trim(), date, createdAt: new Date().toISOString() }; setStore(s => ({ ...s, purchases: [...s.purchases, purchase] })); setAmount(''); setDescription(''); setDate(today()); setError(''); setSuccess(true); onSaved?.() }
 return <form className="panel purchase-form" onSubmit={submit}><h2>Add a purchase</h2><p className="helper-text">This purchase will be saved to the selected list.</p><div className="field-grid"><div className="field"><label htmlFor="purchase-amount">Amount (SYP)</label><input id="purchase-amount" type="number" min="0.01" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setSuccess(false)}} placeholder="0.00" required/></div><div className="field"><label htmlFor="purchase-date">Expense date</label><input id="purchase-date" type="date" value={date} onChange={e=>{setDate(e.target.value);setSuccess(false)}} required/></div><div className="field field--wide"><label htmlFor="purchase-description">Description</label><input id="purchase-description" value={description} onChange={e=>{setDescription(e.target.value);setSuccess(false)}} maxLength={160} placeholder="What did you spend on?" required/></div></div>{error && <p className="form-error" role="alert">{error}</p>}{success && <p className="form-success" role="status">Purchase saved successfully.</p>}<button className="primary-action" type="submit">Save purchase</button></form>
}
function SummaryCards({ total, count }: { total: number; count: number }) { return <div className="summary-grid"><div className="summary-card"><span>Total expenses</span><strong>{money(total)}</strong></div><div className="summary-card"><span>Purchases</span><strong>{count}</strong></div></div> }
function PurchaseRows({ items }: { items: Purchase[] }) { return items.length ? <div className="purchase-table-wrap"><table className="purchase-table"><thead><tr><th>Description</th><th>Date</th><th className="align-right">Amount</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.description}</td><td>{new Date(`${p.date}T12:00:00`).toLocaleDateString()}</td><td className="align-right amount-cell">{money(p.amount)}</td></tr>)}</tbody></table></div> : <div className="empty-state empty-state--compact"><h2>No purchases for this month</h2><p>Add a purchase or select another month to review your expenses.</p></div> }
export function PersonalListOverviewPage() { const d = useListData(); if (!d.list) return <PersonalListLayout><></></PersonalListLayout>; return <PersonalListLayout><div className="overview-toolbar"><MonthPicker month={d.month} onChange={d.setMonth}/><Link className="primary-action link-button" to={`/expenses/personal/${d.listId}/purchases?month=${d.month}#add-purchase`}>＋ Add purchase</Link></div><h2 className="period-title">{d.list.name} expenses — {monthLabel(d.month)}</h2><SummaryCards total={d.total} count={d.purchases.length}/><PurchaseForm listId={d.listId}/><div className="section-title-row"><h2>Recent purchases</h2><Link to={`/expenses/personal/${d.listId}/purchases?month=${d.month}`}>View all</Link></div><PurchaseRows items={d.purchases.slice(0,5)}/></PersonalListLayout> }
export function PersonalListPurchasesPage() { const d = useListData(); return <PersonalListLayout><MonthPicker month={d.month} onChange={d.setMonth}/><h2 className="period-title">Purchases — {monthLabel(d.month)}</h2><SummaryCards total={d.total} count={d.purchases.length}/><div id="add-purchase"><PurchaseForm listId={d.listId}/></div><PurchaseRows items={d.purchases}/></PersonalListLayout> }
export function PersonalListHistoryPage() { const d = useListData(); const all = d.store.purchases.filter(p=>p.listId===d.listId && monthKey(p.date)===d.month).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); return <PersonalListLayout><MonthPicker month={d.month} onChange={d.setMonth}/><h2 className="period-title">Entry history — {monthLabel(d.month)}</h2><p className="page-description">Purchases in the order they were recorded.</p><PurchaseRows items={all}/></PersonalListLayout> }
export function PersonalListAnalysisPage() { const d = useListData(); const byDay = new Map<number,number>(); d.purchases.forEach(p=>{const day=Number(p.date.slice(8,10));byDay.set(day,(byDay.get(day)||0)+p.amount)}); const days = Array.from({length:new Date(Number(d.month.slice(0,4)),Number(d.month.slice(5,7)),0).getDate()},(_,i)=>i+1); const max = Math.max(0,...byDay.values()); return <PersonalListLayout><MonthPicker month={d.month} onChange={d.setMonth}/><h2 className="period-title">Analysis — {monthLabel(d.month)}</h2><SummaryCards total={d.total} count={d.purchases.length}/>{d.purchases.length===0 ? <div className="empty-state empty-state--compact"><h2>No data to analyse</h2><p>Recorded purchases for this month will appear in the chart.</p></div> : <div className="panel chart-panel"><h2>Daily expenses</h2><p className="helper-text">Spending by day of the selected month.</p><div className="bar-chart" role="img" aria-label={`Daily expense chart for ${monthLabel(d.month)}`}>{days.map(day=>{const value=byDay.get(day)||0;return <div className="bar-column" key={day} title={`${day}: ${money(value)}`}><span className="bar-value">{value>0?money(value):''}</span><div className={`bar${value?' bar--active':''}`} style={{height:`${max ? Math.max(value ? 5 : 0, value/max*100) : 0}%`}}/><span className="bar-label">{day}</span></div>})}</div><div className="chart-legend">Daily total · {money(d.total)} for the month</div></div>}</PersonalListLayout> }
const transportTabs = [{ label: 'نظرة عامة', suffix: '' }, { label: 'سجل الرحلات', suffix: '/trips' }, { label: 'التحليل', suffix: '/analysis' }, { label: 'سجل الإدخال', suffix: '/history' }]
const recordTotal = (r: TransportRecord) => r.trips.reduce((sum, t) => sum + t.amount, 0)
const recordTrips = (records: TransportRecord[]) => records.reduce((sum, r) => sum + r.trips.length, 0)
const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('ar', { day: 'numeric', month: 'long', year: 'numeric' })
function TransportLayout({ children }: { children: ReactNode }) {
 const base = '/expenses/personal/transport'
 return <section className="expense-page list-page"><div className="breadcrumb"><Link to="/expenses">المصاريف</Link><span>/</span><Link to="/expenses/personal">المصاريف الشخصية</Link><span>/</span><span>المواصلات</span></div><div className="list-heading"><p className="eyebrow">المصاريف الشخصية</p><h1>المواصلات</h1><p className="page-description">متابعة تكاليف التنقل والرحلات المسجلة.</p></div><nav className="sub-navigation" aria-label="التنقل في المواصلات">{transportTabs.map(t=><NavLink key={t.suffix} to={`${base}${t.suffix}${window.location.search}`} end={!t.suffix} className={({isActive})=>`sub-navigation__link${isActive?' sub-navigation__link--active':''}`}>{t.label}</NavLink>)}</nav><div className="sub-page-content">{children}</div></section>
}
function TransportMonthPicker({month,onChange}:{month:string;onChange:(m:string)=>void}) { return <div className="month-control"><label htmlFor="transport-month">الشهر</label><input id="transport-month" type="month" value={month} onChange={e=>onChange(e.target.value||thisMonth())}/></div> }
function TransportMetrics({records}:{records:TransportRecord[]}) { const total=records.reduce((s,r)=>s+recordTotal(r),0); const count=recordTrips(records); const days=new Set(records.map(r=>r.date)).size; return <div className="summary-cards"><div className="summary-card"><span>إجمالي التكلفة</span><strong>{money(total)}</strong></div><div className="summary-card"><span>عدد الرحلات</span><strong>{count}</strong></div><div className="summary-card"><span>متوسط الرحلة</span><strong>{count?money(total/count):'—'}</strong></div><div className="summary-card"><span>أيام التنقل</span><strong>{days}</strong></div></div> }
function TransportRecordList({records,onEdit,onDelete,showCreated=false}:{records:TransportRecord[];onEdit:(r:TransportRecord)=>void;onDelete:(r:TransportRecord)=>void;showCreated?:boolean}) {
 const [selected,setSelected] = useState<TransportRecord|null>(null)
 const selectedCurrent = selected ? records.find(r=>r.id===selected.id) : undefined
 useEffect(()=>{ if(selected && !records.some(r=>r.id===selected.id)) setSelected(null) },[records,selected])
 return <div className="transport-records">
 {records.length===0 ? <div className="empty-state empty-state--compact"><h2>لا توجد سجلات في هذه الفترة</h2><p>ستظهر هنا الرحلات التي تسجلها.</p></div> :
 <div className="purchase-table-wrap transport-table-wrap"><table className="purchase-table transport-table"><thead><tr><th>التاريخ</th><th>عدد الرحلات</th><th className="align-right">المبلغ الإجمالي</th>{showCreated&&<th>وقت الإدخال</th>}</tr></thead><tbody>
 {records.map(r=><tr key={r.id} className="transport-record-row" tabIndex={0} onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r)}}} aria-label={`عرض سجل ${dateLabel(r.date)}`}><td>{dateLabel(r.date)}</td><td>{r.trips.length}</td><td className="align-right amount-cell">{money(recordTotal(r))}</td>{showCreated&&<td>{r.createdAt?new Date(r.createdAt).toLocaleString('ar'):'غير متوفر'}</td>}</tr>)}
 </tbody></table></div>}
 {selectedCurrent&&<div className="transport-modal-backdrop" role="presentation" onClick={()=>setSelected(null)}><section className="panel transport-modal" role="dialog" aria-modal="true" aria-labelledby="transport-record-title" onClick={e=>e.stopPropagation()}><div className="transport-modal-heading"><h2 id="transport-record-title">تفاصيل سجل الرحلات</h2><button type="button" className="transport-close" onClick={()=>setSelected(null)} aria-label="إغلاق">×</button></div><p className="helper-text">{dateLabel(selectedCurrent.date)} · {selectedCurrent.trips.length} رحلة</p><div className="transport-record-details"><ul>{selectedCurrent.trips.map((t,i)=><li key={t.id}>رحلة {i+1} — {t.type==='Outbound'?'ذهاب':'عودة'}: <strong>{money(t.amount)}</strong></li>)}</ul></div><div className="transport-actions"><button type="button" className="secondary-action" onClick={()=>{const r=selectedCurrent;setSelected(null);onEdit(r)}}>تعديل السجل</button><button type="button" className="transport-delete-action" onClick={()=>{const r=selectedCurrent;if(window.confirm(`هل أنت متأكد من حذف السجل المحدد بتاريخ ${dateLabel(r.date)}؟ لا يمكن التراجع عن هذا الإجراء.`)){onDelete(r);setSelected(null)}}}>حذف السجل</button></div></section></div>}
 </div>
}
export function TransportExpensesPage() {
 const {store,setStore}=useStore(); const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const path=window.location.pathname; const page=path.endsWith('/trips')?'trips':path.endsWith('/analysis')?'analysis':path.endsWith('/history')?'history':'overview'; const month=params.get('month')||thisMonth(); const setMonth=(m:string)=>setParams(prev=>{const p=new URLSearchParams(prev);p.set('month',m);return p},{replace:true});
 const [date,setDate]=useState(today()); const [count,setCount]=useState(0); const [trips,setTrips]=useState<{id:string;type:'Outbound'|'Return';amount:string}[]>([]); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [editing,setEditing]=useState<string|null>(null);
 const allRecords=store.transportRecords; const monthly=allRecords.filter(r=>monthKey(r.date)===month); const ordered=useMemo(()=>[...monthly].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)),[monthly]); const history=useMemo(()=>[...allRecords].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')),[allRecords]);
 useEffect(()=>{const id=params.get('edit');if(id){const r=store.transportRecords.find(x=>x.id===id);if(r){setEditing(r.id);setDate(r.date);setCount(r.trips.length);setTrips(r.trips.map(t=>({...t,amount:String(t.amount)})));}}},[params,store.transportRecords]);
 const changeCount=(n:number)=>{if(n<trips.length&&trips.slice(n).some(t=>t.amount.trim()))if(!window.confirm('سيؤدي تقليل عدد الرحلات إلى حذف بيانات الرحلات الزائدة. هل تريد المتابعة؟'))return;setTrips(prev=>Array.from({length:n},(_,i)=>prev[i]||{id:`${Date.now()}-${i}-${Math.random()}`,type:'Outbound' as const,amount:''}));setCount(n);setError('')};
 const reset=()=>{setDate(today());setCount(0);setTrips([]);setEditing(null);setError('');setSuccess('');setParams(prev=>{const p=new URLSearchParams(prev);p.delete('edit');return p},{replace:true})};
 const save=(e:FormEvent)=>{e.preventDefault();if(!date||Number.isNaN(new Date(`${date}T12:00:00`).getTime())){setError('يرجى اختيار تاريخ صحيح.');return}if(!trips.length){setError('اختر عدد الرحلات أولاً.');return}if(trips.some(t=>!t.amount.trim()||!Number.isFinite(Number(t.amount))||Number(t.amount)<=0)){setError('أدخل تكلفة صحيحة أكبر من صفر لكل رحلة.');return}const record:TransportRecord={id:editing||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,date,trips:trips.map(t=>({id:t.id,type:t.type,amount:Math.round(Number(t.amount)*100)/100})),createdAt:editing?store.transportRecords.find(r=>r.id===editing)?.createdAt||new Date().toISOString():new Date().toISOString()};setStore(s=>({...s,transportRecords:editing?s.transportRecords.map(r=>r.id===editing?record:r):[...s.transportRecords,record]}));const message=editing?'تم تحديث سجل المواصلات.':'تم حفظ سجل المواصلات.';reset();setSuccess(message)};
 const edit=(r:TransportRecord)=>{navigate(`/expenses/personal/transport?month=${month}&edit=${encodeURIComponent(r.id)}`);window.scrollTo({top:0,behavior:'smooth'})}; const remove=(r:TransportRecord)=>{if(window.confirm('هل تريد حذف سجل المواصلات هذا؟'))setStore(s=>({...s,transportRecords:s.transportRecords.filter(x=>x.id!==r.id)}))};
 const allMonths=[...new Set(allRecords.map(r=>monthKey(r.date)))].sort(); const total=monthly.reduce((s,r)=>s+recordTotal(r),0); const tripCount=recordTrips(monthly); const dayTotals=new Map<string,number>();monthly.forEach(r=>dayTotals.set(r.date,(dayTotals.get(r.date)||0)+recordTotal(r))); const days=Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);const maxDaily=Math.max(0,...dayTotals.values()); const monthlyTotals=allMonths.map(m=>({month:m,total:allRecords.filter(r=>monthKey(r.date)===m).reduce((s,r)=>s+recordTotal(r),0),trips:recordTrips(allRecords.filter(r=>monthKey(r.date)===m))}));
 return <TransportLayout><TransportMonthPicker month={month} onChange={setMonth}/>
 {page==='overview'&&<><h2 className="period-title">نظرة عامة — {monthLabel(month)}</h2><TransportMetrics records={monthly}/><form className="panel purchase-form" onSubmit={save}><h2>{editing?'تعديل سجل المواصلات':'تسجيل رحلات جديدة'}</h2><p className="helper-text">يمكن تسجيل عدة رحلات في اليوم نفسه، مع اختيار نوع وتكلفة كل رحلة.</p><div className="field-grid"><div className="field"><label htmlFor="transport-date">تاريخ الرحلات</label><input id="transport-date" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></div><div className="field"><label htmlFor="trip-count">عدد الرحلات</label><select id="trip-count" value={count} onChange={e=>changeCount(Number(e.target.value))}><option value={0}>اختر عدد الرحلات</option>{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></div></div>{trips.length>0&&<div className="trip-fields">{trips.map((t,i)=><div className="trip-row" key={t.id}><strong>رحلة {i+1}</strong><div className="field"><label htmlFor={`trip-type-${t.id}`}>نوع الرحلة</label><select id={`trip-type-${t.id}`} value={t.type} onChange={e=>setTrips(prev=>prev.map(x=>x.id===t.id?{...x,type:e.target.value as 'Outbound'|'Return'}:x))}><option value="Outbound">ذهاب</option><option value="Return">عودة</option></select></div><div className="field"><label htmlFor={`trip-cost-${t.id}`}>التكلفة (SYP)</label><input id={`trip-cost-${t.id}`} type="number" min="0.01" step="any" value={t.amount} onChange={e=>setTrips(prev=>prev.map(x=>x.id===t.id?{...x,amount:e.target.value}:x))} placeholder="0"/></div></div>)}<div className="transport-live-total"><span>إجمالي اليوم</span><strong>{money(trips.reduce((s,t)=>s+(Number(t.amount)>0?Number(t.amount):0),0))}</strong></div></div>}{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p className="form-success" role="status">{success}</p>}<div className="transport-actions"><button className="primary-action" type="submit">{editing?'حفظ التعديلات':'حفظ سجل الرحلات'}</button>{editing&&<button className="secondary-action" type="button" onClick={reset}>إلغاء التعديل</button>}</div></form><div className="overview-toolbar"><h2 className="period-title">أحدث سجلات التنقل</h2><Link to={`/expenses/personal/transport/trips?month=${month}`}>عرض سجل الرحلات الكامل ←</Link></div><TransportRecordList records={ordered.slice(0,5)} onEdit={edit} onDelete={remove}/></>}
 {page==='trips'&&<><h2 className="period-title">سجل الرحلات — {monthLabel(month)}</h2><TransportMetrics records={monthly}/><TransportRecordList records={ordered} onEdit={edit} onDelete={remove}/></>}
 {page==='history'&&<><h2 className="period-title">سجل الإدخال</h2><p className="page-description">مرتبة حسب وقت تسجيل السجل في التطبيق، وليس حسب تاريخ الرحلة.</p><TransportRecordList records={history} onEdit={edit} onDelete={remove} showCreated/></>}
 {page==='analysis'&&<><h2 className="period-title">تحليل المواصلات — {monthLabel(month)}</h2><TransportMetrics records={monthly}/>{!allRecords.length?<div className="empty-state empty-state--compact"><h2>لا توجد بيانات للتحليل بعد</h2><p>سجّل رحلاتك لتظهر المؤشرات والرسوم البيانية هنا.</p></div>:<><div className="panel chart-panel"><h2>الإنفاق اليومي</h2><p className="helper-text">تكلفة الرحلات حسب يوم حدوثها.</p>{!monthly.length?<p className="helper-text">لا توجد رحلات مسجلة في الشهر المختار.</p>:<div className="bar-chart" role="img" aria-label={`الإنفاق اليومي لشهر ${monthLabel(month)}`}>{days.map(d=>{const v=dayTotals.get(d)||0;return <div className="bar-column" key={d} title={`${d}: ${money(v)}`}><span className="bar-value">{v?money(v):''}</span><div className={`bar${v?' bar--active':''}`} style={{height:`${maxDaily?Math.max(v?5:0,v/maxDaily*100):0}%`}}/><span className="bar-label">{Number(d.slice(-2))}</span></div>})}</div>}<div className="chart-legend">إجمالي الشهر: {money(total)}</div></div><div className="panel chart-panel"><h2>مقارنة الإنفاق بين الأشهر</h2><div className="transport-month-comparison">{monthlyTotals.map(m=><div className="transport-month-row" key={m.month}><span>{monthLabel(m.month)}</span><div className="transport-month-track"><div className="transport-month-fill" style={{width:`${Math.max(...monthlyTotals.map(x=>x.total),1)?m.total/Math.max(...monthlyTotals.map(x=>x.total),1)*100:0}%`}}/></div><strong>{money(m.total)}</strong></div>)}</div></div><div className="panel chart-panel"><h2>عدد الرحلات وتكلفتها حسب الشهر</h2><p className="helper-text">تُعرض فقط الأشهر التي تحتوي على سجلات فعلية.</p><div className="transport-month-comparison">{monthlyTotals.map(m=><div className="transport-month-row" key={m.month}><span>{monthLabel(m.month)}</span><span>{m.trips} رحلة</span><strong>{money(m.total)}</strong></div>)}</div></div></>}</>}
 </TransportLayout>
}

export function AddExpensePage() { const { store } = useStore(); const navigate = useNavigate(); const [listId,setListId] = useState(''); useEffect(()=>{ if (!listId && store.lists.length) setListId(store.lists[0].id) },[store.lists,listId]); return <section className="expense-page"><div className="page-heading"><p className="eyebrow">Personal Expenses</p><h1>Add expense</h1><p className="page-description">Choose the personal expense list where this purchase belongs.</p></div>{!store.lists.length ? <div className="empty-state"><h2>Create a list first</h2><p>Purchases must belong to a personal expense list.</p><Link className="secondary-action link-button" to="/expenses/personal">Go to personal expenses</Link></div> : <div className="panel"><div className="field"><label htmlFor="target-list">Expense list</label><select id="target-list" value={listId} onChange={e=>setListId(e.target.value)}>{store.lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><button className="primary-action" onClick={()=>navigate(`/expenses/personal/${listId}`)}>Continue to {store.lists.find(l=>l.id===listId)?.name || 'list'}</button></div>}</section> }
